services:
  app:
    image: rpungello/ytdl-sub-manager:latest
    ports:
      - "${WEB_PORT:-80}:80"
    restart: unless-stopped
    environment:
      - APP_KEY="${APP_KEY}"
    volumes:
      - /path/to/ytdl-sub-config:/config
